### ISSUE TITLE
Hoe to close aSide ?

### ISSUE THREAD

**Issue by marcolino** [dbtek/angular-aside#10]
I don't know if the intended behaviour of "Ok" and "Cancel" buttons in your aSide demo is to close the sidebar, but they do not close it... How can I programmatically force the closure of the aside sidebar (using a button, for instance, and not clicking outside the sidebar...)?

**Comment by dbtek** [comment]
As it's documented on [ui-bootstrap](http://angular-ui.github.io/bootstrap/#/modal):

>The open method returns a modal instance, an object with the following properties:
close(result) - a method that can be used to close a modal, passing a result
dismiss(reason) - a method that can be used to dismiss a modal, passing a reason
result - a promise that is resolved when a modal is closed and rejected when a modal is dismissed
opened - a promise that is resolved when a modal gets opened after downloading content's template and resolving all variables

`$dismiss()` and `$close()` methods are only available inside the aside.

**Comment by marcolino** [comment]
sorry, I was using a wrong markup... :-)
