### ISSUE TITLE
Shift Page when Aside is opened as option.

### ISSUE THREAD

**Issue by dcbartlett** [dbtek/angular-aside#12]
"aside-open" should be added to ```<body>``` when the aside is opened so that it can be used to shift the content when the aside is opened (force over by the aside).  It would be awesome if that was an option on the $aside.open() method call.

**Comment by dbtek** [comment]
There are `template` and `templateUrl` properties if you are talking about setting content of the aside. Sorry, but it's not clear.

**Comment by dcbartlett** [comment]
what i am meaning is,

When you open the menu, it should shift the current view over.  So if the menu is 300px, the original page from before the aside is opened, should shift over 300 px and then the aside will show, giving the appearance that the aside "PUSH" the page over.

**Comment by dcbartlett** [comment]
also i noticed that github processed ```<body>``` in my original post, that probably made it a bit more confusing.  lol

**Comment by dbtek** [comment]
You should be doing this viewport positioning in your app by conditionally applying css rules with aside state.
