### ISSUE TITLE
Feature Request: Optional Overlay

### ISSUE THREAD

**Issue by harbhub** [dbtek/angular-aside#13]
I would like to be able to have an overlay cover the remaining screen portion when the aside opens.  When the aside closes, then the overlay should also disappear.  Is this feature request something that seems doable?  Does it already exist and I'm just unaware?  Would I be able to fork this repository and attempt to create this functionality?  Thanks!

**Comment by dbtek** [comment]
Hi @harbhub,

Aside is a modal instance, so there is already a backdrop (assuming you mean it by overlay). In demo [plank](http://plnkr.co/edit/G7vMSv?p=preview) please notice the `backdrop: false` option. It's true on default.
