### ISSUE TITLE
How to close $aside modal programmatically?

### ISSUE THREAD

**Issue by gerbil** [dbtek/angular-aside#16]

**Comment by dbtek** [comment]
`open` method returns a modal instance. Please see [angular-ui.github.io/bootstrap/#/modal](http://angular-ui.github.io/bootstrap/#/modal).

**Comment by leolux** [comment]
I cannot access the modal directly to call close(result) because you extend the modal service. Any code showing how to close the sidebar would be nice.

**Comment by leolux** [comment]
TypeError: $aside.close is not a function

**Comment by leolux** [comment]
@dbtek: Although this issue has been closed, I wasn't able to get it working (close $aside programmatically)

**Comment by dbtek** [comment]
$aside does not gide you a modal instance. Hop did you end ip without this?

Like I said, open method **returns an instance**.

```
asideInstance = $aside.open(opts);
asideInstance.close();
```

**Comment by dbtek** [comment]
Again, please read $modal docs [angular-ui.github.io/bootstrap/#/modal](http://angular-ui.github.io/bootstrap/#/modal).

**Comment by leolux** [comment]
The following code does not work because asideInstance.close is not a function:
```
var ModalInstanceCtrl = function ($scope, $modalInstance) {
        $scope.ok = function (e) {
          $modalInstance.close();
          e.stopPropagation();
        };
        $scope.cancel = function (e) {
          $modalInstance.dismiss();
          e.stopPropagation();
        };
      };
      ModalInstanceCtrl.$inject = ['$scope', '$modalInstance'];

      var asideInstance ;

      $scope.root.openAside = function (position, backdrop) {
        $scope.root.asideState = {
          open: true,
          position: position
        };

        function postClose() {
          $scope.root.asideState.open = false;
        }

        asideInstance  = $aside.open({
          templateUrl: '../w/templates/aside.html',
          placement: position,
          size: 'sm',
          backdrop: backdrop,
          controller: ModalInstanceCtrl,
          scope: $scope
        }).result.then(postClose, postClose);
      };

      $scope.root.closeAside = function () {
        asideInstance.close();
      }
```

**Comment by leolux** [comment]
Any idea why the code above does not work?

**Comment by leolux** [comment]
The error for the code above is:
``
TypeError: $scope.root.asideInstance.close is not a function
    at $scope.root.closeAside (root.js:151)
    at $parseFunctionCall (angular.js:12345)
    at element.on.callback (angular.js:21438)
    at Scope.$eval (angular.js:14401)
    at Scope.$apply (angular.js:14500)
    at HTMLAnchorElement.<anonymous> (angular.js:21443)
    at HTMLAnchorElement.eventHandler (angular.js:3014)
``
@dbtek: FYI

**Comment by dbtek** [comment]
You insist on not reading. Here a working example, http://plnkr.co/edit/VT5VP4?p=preview.

**Comment by leolux** [comment]
Alright thank you! I have found the mistake in my code above by comparing it to your example.
The following line didn't return the instance correctly:
```
}).result.then(postClose, postClose);
```
The corresponding line in the working example:
```
`});
      $scope.asideInstance.result.then(postClose, postClose);
```
Currently I know three working examples:
http://plnkr.co/edit/G7vMSv?p=preview (uses ng-click="cancel($event)")
http://plnkr.co/edit/VT5VP4?p=preview. (also uses the controller method ng-click="cancel($event)")
http://plnkr.co/edit/0DuT86bq1qxnZ0snlAPr?p=preview (actually uses the instance variable $scope.asideInstance)
