### ISSUE TITLE
Body shrinks together

### ISSUE THREAD

**Issue by leolux** [dbtek/angular-aside#17]
When using the folllowing css rule for the body class,
``
.modal-open.left {
  padding-left: 320px;
}
``
the body moves 320 px to the right but the body content shrinks by 320 px, which looks bad on small screens. The left side of the body does not slide over the border of the html document.

How to slide the body to the side withouth shrinking the body?

**Comment by dbtek** [comment]
It's about where you want to place your content when aside is opened.
The css you quoted is written in demo app, not in angular-aside. This means you should write it with the way you want to.

**Comment by leolux** [comment]
Well, I think that an off-screen body would be an important enhancement. Look around for other off-screen side menu frameworks. Most of them has this feature without shrinking the body.

I am struggling with css stuff all the time, so maybe someone else knows a way how to achive this :-)

**Comment by leolux** [comment]
@dbtek Maybe this could be tracked as an enhancement?
