### ISSUE TITLE
ui-bootstrap-tpls-0.13.0.js closing animation problem

### ISSUE THREAD

**Issue by sdemircom** [dbtek/angular-aside#19]
ui-bootstrap-tpls-0.13.0.js ile çalışırken animasyon ile açılan yan panel, kapanırken animasyonsuz birden kapanıyor. ui-bootstrap-tpls-0.12.1.js ile bu problem yok.

**Comment by DBardaji** [comment]
I have the same problem! When I click close in the off-canvas menu, the black translucent still there and i can't click in no place of my web site.

**Comment by dbtek** [comment]
Related to #20

**Comment by lumpo** [comment]
Is there any progress on this issue? Even a temp. workaround?

**Comment by dbtek** [comment]
No, not yet. I didn't have time to look into.

**Comment by dbtek** [comment]
Hi,

This issue is not fully related to angular-aside itself. Because default animation bundled with library works perfectly.

The problem here I guess a custom animation used in the [plunk](http://plnkr.co/edit/G7vMSv?p=preview). Am I right?
