### ISSUE TITLE
Support angular-bootstrap 0.13.0

### ISSUE THREAD

**Issue by bdwain** [dbtek/angular-aside#20]
It'd be great if this supported angular-bootstrap 0.13.0. It was released recently and it's the first version that supports upgrading from angular 1.2 to 1.3/1.4.

**Comment by kiempoturner** [comment]
Same issue

**Comment by priyankmundragmail** [comment]
same issue

**Comment by hmartos** [comment]
Suscribed to this thread, I will use this module when this is fixed

**Comment by marsanla** [comment]
I am using 0.13.4 and is not working

**Comment by dbtek** [comment]
Hey guys! I hardly had time to look into this. I'm happy to announce, today [version 1.2.0](https://github.com/dbtek/angular-aside/releases/tag/1.2.0) is released.

Enjoy!
