### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by bdkent** [dbtek/angular-aside#24]
I have a couple of feature requests for ng-aside:
1. Allow the _inside_ side to be optionally resizeable, ideally with a custom bit of HTML to act as a handle. For example, if the aside is anchored to the _right_ side then the _left_ has a widget to allow of resizing horizontally. The template could have a `aside-resize-handle` section to act as the anchor for the interaction.
2. I would love if there could be an option where the underlying content behind the aside (the main page) was still able to be interacted with. I understand that having based the implementation on the `modal`, might present some inherent difficulties, but it would be a great option to have.

Thanks!

**Comment by jagged3dge** [comment]
Also, it'd be great to have the menu render *above* the content, instead of *pushing* it either way. I doubt it'd be tough, but it'd be cool to have out-of-the-box.
