### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by mattlewis92** [dbtek/angular-aside#27]
Hi, any chance you could publish this module to npm?

It should be as simple as adding this to your package.json:
```
...
browser: "dist/js/angular-aside.js",
style: "dist/css/angular-aside.css",
...
```

and then running `npm publish`.

Thanks!

**Comment by dbtek** [comment]
Hi @mattlewis92,

Sure! However I was planning to publish it in the way angular does. A main file which requires browser file and exports a string which is the module name.

So it will be possible to do:

```js
angular.module('myApp', [
  require('angular-aside')
]);
```

What is `style` field used for? Are there any references?

**Comment by mattlewis92** [comment]
Ah yeah I realised my oversight and implemented it that way in my PR.

The `style` field is a non standardised convention used by several tools, more info [here](http://stackoverflow.com/questions/32037150/style-field-in-package-json).
