### ISSUE TITLE
Error: [$injector:strictdi] function($modal) is not using explicit annotation and cannot be invoked in strict mode

### ISSUE THREAD

**Issue by saaqibz** [dbtek/angular-aside#30]
Hello,
I'm using gulp-angular yeoman generator to build an angular app with the options of . I tried using ngAside but ran into an issue where it wouldn't load because it's looking for  explicit annotation of $modal. I do not call modal anywhere else. Any idea how this can be fixed? Here's the error below from firefox.

"Error: [$injector:strictdi] function($modal) is not using explicit annotation and cannot be invoked in strict mode
http://errors.angularjs.org/1.4.7/$injector/strictdi?p0=function(%24modal)
minErr/<@http://localhost:3000/bower_components/angular/angular.js:68:12
annotate@http://localhost:3000/bower_components/angular/angular.js:3747:1
invoke@http://localhost:3000/bower_components/angular/angular.js:4456:21
enforcedReturnValue@http://localhost:3000/bower_components/angular/angular.js:4330:20
invoke@http://localhost:3000/bower_components/angular/angular.js:4478:14
createInjector/instanceCache.$injector<@http://localhost:3000/bower_components/angular/angular.js:4295:20
getService@http://localhost:3000/bower_components/angular/angular.js:4437:39
invoke@http://localhost:3000/bower_components/angular/angular.js:4469:1
instantiate@http://localhost:3000/bower_components/angular/angular.js:4486:27
$ControllerProvider/this.$get</<@http://localhost:3000/bower_components/angular/angular.js:9151:18
$ViewDirectiveFill/<.compile/<@http://localhost:3000/bower_components/angular-ui-router/release/angular-ui-router.js:4018:28
invokeLinkFn@http://localhost:3000/bower_components/angular/angular.js:8789:9
nodeLinkFn@http://localhost:3000/bower_components/angular/angular.js:8289:1
compositeLinkFn@http://localhost:3000/bower_components/angular/angular.js:7680:13
publicLinkFn@http://localhost:3000/bower_components/angular/angular.js:7555:30
updateView@http://localhost:3000/bower_components/angular-ui-router/release/angular-ui-router.js:3959:23
$ViewDirective/directive.compile/</<@http://localhost:3000/bower_components/angular-ui-router/release/angular-ui-router.js:3921:11
$RootScopeProvider/this.$get</Scope.prototype.$broadcast@http://localhost:3000/bower_components/angular/angular.js:16311:15
transitionTo/$state.transition<@http://localhost:3000/bower_components/angular-ui-router/release/angular-ui-router.js:3311:11
processQueue@http://localhost:3000/bower_components/angular/angular.js:14745:28
scheduleProcessQueue/<@http://localhost:3000/bower_components/angular/angular.js:14761:27
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://localhost:3000/bower_components/angular/angular.js:15989:16
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://localhost:3000/bower_components/angular/angular.js:15800:15
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:3000/bower_components/angular/angular.js:16097:13
done@http://localhost:3000/bower_components/angular/angular.js:10546:36
completeRequest@http://localhost:3000/bower_components/angular/angular.js:10744:7
requestLoaded@http://localhost:3000/bower_components/angular/angular.js:10685:1
" "<div data-ng-animate="1" class="ng-scope" ui-view="">"

**Comment by dbtek** [comment]
You have enabled `ng-strict-di`. This is most probably why you get this error.

**Comment by fassetar** [comment]
+1

**Comment by artvlasov** [comment]
I've met the same trouble, and simply fixed using ```$uibModal``` name.
```
-    .factory('$aside', function($uibModal) {
+    .factory('$aside', ['$uibModal', function($uibModal) {
```
I can't disable strictDi mode, and I think I'm not alone with that.

**Comment by bastienmoulia** [comment]
I just made a pull request to integrate that.
