### ISSUE TITLE
$modalInstance is now deprecated. Use $uibModalInstance instead.

### ISSUE THREAD

**Issue by pkyad** [dbtek/angular-aside#34]
Even after using the latest version I get the following message in the console.

**Comment by dbtek** [comment]
Then use `$uibModalInstance` instead of `$modalInstance` in your aside's controller. :smile: 

$modalInstance is deprecated after ui-bootstrap 0.14.3 or newer versions. Just switch to new service. (demo [plunk](http://plnkr.co/edit/G7vMSv?p=preview) updated).
