### ISSUE TITLE
Modal on top of Aside

### ISSUE THREAD

**Issue by rschenkel** [dbtek/angular-aside#54]
Is there a way to have a modal on top of the Aside.  When I try and click a modal it opens below the aside.

**Comment by dbtek** [comment]
Please check z-index values.

**Comment by rschenkel** [comment]
Hi @dbtek ... I'm sorry but I was wondering if you could help me a little more with this.  I tried adding the following the the $uibModal.open:

backdropClass: 'modal-on-modal',

And added the following to my css file:

.modal-backdrop.modal-on-modal { z-index: 20000; }
