### ISSUE TITLE
The side menu is empty if the templateUrl content include inner directives

### ISSUE THREAD

**Issue by idanb11** [dbtek/angular-aside#9]
Hi @dbtek , great job.

I'm trying to use this library, but if I include directives in the templateUrl content- the side menu is empty. 
The directive I'm trying to use in the templateUrl content is Accordion which is part of the augular-ui library.
any help will be great.
Idanb11

**Comment by dbtek** [comment]
Hi @idanb11,

I think it's related to something else. I successfully used accordion inside aside. You can see it in [this plunk](http://plnkr.co/edit/weu2JB?p=preview).

**Comment by idanb11** [comment]
OK, I see.
My problem is because I'm trying to access something from the main controller scope inside the templateUrl content
